-- Migration v8: Add move slots to encounters
ALTER TABLE encounters
  ADD COLUMN IF NOT EXISTS move_1 TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS move_2 TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS move_3 TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS move_4 TEXT DEFAULT NULL;
