// SoulDex data layer (P0). The bundled compact index (generated by scripts/gen-dex.mjs)
// powers INSTANT, OFFLINE browse + search. Sprites + heavy detail load lazily from the
// CDN/PokéAPI and get cached (see dexCache + getPokemonDetail later). Bilingual day one.

import RAW from '../../data/pokedex.json'

export interface DexEntry {
  id: number
  de: string
  en: string
  t: string[]        // type slugs, in slot order
  s: number[]        // base stats: [hp, atk, def, spa, spd, spe]
  g: number          // generation
}

export const DEX = RAW as DexEntry[]
const BY_ID = new Map(DEX.map((e) => [e.id, e]))
export function dexEntry(id: number): DexEntry | undefined { return BY_ID.get(id) }

// Resolve a species NAME (DE or EN, case-insensitive) → national-dex id. Lets run
// surfaces that only store a name (encounters) open the right Quick-Look/SoulDex page.
const normName = (s: string) => s.toLowerCase().trim()
const NAME_TO_ID = new Map<string, number>()
for (const e of DEX) { NAME_TO_ID.set(normName(e.de), e.id); NAME_TO_ID.set(normName(e.en), e.id) }
export const dexIdByName = (name: string | null | undefined): number | null => (name ? NAME_TO_ID.get(normName(name)) ?? null : null)

export type Lang = 'de' | 'en'
export function dexName(e: DexEntry, lang: Lang): string { return lang === 'de' ? e.de : e.en }
export const STAT_LABEL: Record<Lang, string[]> = {
  de: ['KP', 'Ang', 'Vert', 'SpA', 'SpV', 'Init'],
  en: ['HP', 'Atk', 'Def', 'SpA', 'SpD', 'Spe'],
}
export const statTotal = (e: DexEntry) => e.s.reduce((a, b) => a + b, 0)
export const GENS = [...new Set(DEX.map((e) => e.g))].sort((a, b) => a - b)

// Official artwork (cards/detail) + small sprite (grid) + shiny — from the PokéAPI CDN.
const CDN = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon'
export const artUrl = (id: number) => `${CDN}/other/official-artwork/${id}.png`
export const shinyArtUrl = (id: number) => `${CDN}/other/official-artwork/shiny/${id}.png`
export const spriteUrl = (id: number) => `${CDN}/${id}.png`

// ── Types: slug → bilingual label + brand color (matches the live tracker) ──────
export const TYPE_DE: Record<string, string> = {
  normal: 'Normal', fire: 'Feuer', water: 'Wasser', electric: 'Elektro', grass: 'Pflanze',
  ice: 'Eis', fighting: 'Kampf', poison: 'Gift', ground: 'Boden', flying: 'Flug',
  psychic: 'Psycho', bug: 'Käfer', rock: 'Gestein', ghost: 'Geist', dragon: 'Drache',
  dark: 'Unlicht', steel: 'Stahl', fairy: 'Fee',
}
const cap = (s: string) => s.charAt(0).toUpperCase() + s.slice(1)
export function typeLabel(slug: string, lang: Lang): string { return lang === 'de' ? (TYPE_DE[slug] || cap(slug)) : cap(slug) }
export const ALL_TYPES = Object.keys(TYPE_DE)
const TYPE_COLOR: Record<string, string> = {
  normal: '#9099a1', fire: '#ff9d55', water: '#4d90d5', electric: '#f4d23c', grass: '#63bc5a',
  ice: '#73cec0', fighting: '#ce4069', poison: '#ab6ac8', ground: '#d97746', flying: '#8fa9de',
  psychic: '#fa7179', bug: '#90c12c', rock: '#c7b78b', ghost: '#5269ad', dragon: '#0b6dc3',
  dark: '#5a5366', steel: '#5a8ea1', fairy: '#ec8fe6',
}
export const typeColor = (slug: string) => TYPE_COLOR[slug] || '#888'

// ── Search + filter over the bundled index (synchronous, offline) ───────────────
export interface DexFilter { types?: string[]; gens?: number[] }
export function searchDex(query: string, f: DexFilter = {}): DexEntry[] {
  const q = query.trim().toLowerCase()
  return DEX.filter((e) => {
    if (f.types && f.types.length && !f.types.every((t) => e.t.includes(t))) return false
    if (f.gens && f.gens.length && !f.gens.includes(e.g)) return false
    if (!q) return true
    return e.de.toLowerCase().includes(q) || e.en.toLowerCase().includes(q) || String(e.id) === q || `#${e.id}` === q
  })
}
