import type { Story } from './types'

// ─────────────────────────────────────────────────────────────────────────────
// Pokémon Platin · Sinnoh — vollständiger Hauptpfad (Zweiblattdorf → Cynthia).
//
// Reine DATEN. Die Engine (lib/story/index.ts) und der Renderer (StoryGuide.tsx)
// sind vollständig generisch — eine neue Edition = neue Datei nach diesem Muster
// + Eintrag in STORIES. Keine Code-Änderung nötig.
//
// Hinweis: Level-Empfehlungen sind Platin-Richtwerte (ungefähr). Arena-Asse und
// Typ-Empfehlungen sind die spielentscheidenden Eckdaten — bewusst kurz gehalten
// (kein Wiki). Inhalte sind editierbar; Korrekturen sind reine Daten-Edits.
// ─────────────────────────────────────────────────────────────────────────────
export const platinum: Story = {
  game: 'platinum',
  label: 'Pokémon Platin',
  region: 'Sinnoh',
  aliases: ['Platin', 'Pokémon Platin', 'Pokemon Platin', 'Platinum'],
  chapters: [
    {
      id: 'zweiblattdorf', title: 'Zweiblattdorf', kind: 'town',
      locations: ['Zweiblattdorf', 'Twinleaf Town', 'Twinleaf'],
      goal: 'Wähle deinen Starter und erreiche Sandgemmenstadt.',
      recommendedLevel: [5, 6],
      todos: ['Mit dem Rivalen zum See Vryheit', 'Starter aus Prof. Eibes Koffer wählen (Chelast / Panflam / Plinfa)', 'Über Route 201 nach Sandgemmenstadt'],
      items: [{ name: 'Trank', note: 'Im eigenen Haus' }],
      encounters: ['Route 201'],
    },
    {
      id: 'sandgemmenstadt', title: 'Sandgemmenstadt', kind: 'town',
      locations: ['Sandgemmenstadt', 'Sandgem Town', 'Sandgem'],
      goal: 'Hol dir den Pokédex von Prof. Eibe.',
      recommendedLevel: [5, 7],
      todos: ['Pokédex von Prof. Eibe erhalten', '5 Pokébälle abholen', 'Über Route 202 nach Jubelstadt'],
      items: [{ name: '5× Pokéball', note: 'Von Eibes Assistent' }, { name: 'Stadtplan' }],
      encounters: ['Route 201', 'Route 202'],
    },
    {
      id: 'jubelstadt', title: 'Jubelstadt', kind: 'town',
      locations: ['Jubelstadt', 'Jubilife City', 'Jubilife'],
      goal: 'Erhalte die Pokétch-Uhr und besiege deinen Rivalen.',
      recommendedLevel: [7, 9],
      todos: ['3 Coupons der Klettermaxe-Werbung sammeln', 'Pokétch abholen', 'Rivalenkampf gewinnen', 'Schein-Detektor vom Internat-Mann'],
      trainers: [
        { name: 'Rivale', title: 'Freundschaftskampf', team: [{ name: 'Staralili', level: 8 }, { name: 'Starter', level: 9 }] },
      ],
      items: [{ name: 'Pokétch' }, { name: 'Beutel mit Charms' }],
      hiddenItems: [{ name: 'Versteckter Trank' }],
      optionalAreas: ['Trainerschule', 'GTS (später)'],
      encounters: ['Route 202', 'Route 203'],
    },
    {
      id: 'route203-erzbergwerk', title: 'Route 203 & Erzbergwerk', kind: 'cave',
      locations: ['Route 203', 'Erzbergwerk', 'Oreburgh-Mine', 'Oreburgh Mine', 'Oreburgh Gate'],
      goal: 'Durchquere das Erzbergwerk und finde Veit in der Mine.',
      recommendedLevel: [9, 12],
      todos: ['Trainer auf Route 203 besiegen', 'Erzbergwerk durchqueren', 'Veit in der Kohlemine finden', 'VM06 Zertrümmerer-Helfer nutzen'],
      items: [{ name: 'Fluchtseil' }, { name: 'Tränke (Route 203)' }],
      hiddenItems: [{ name: 'Versteckter Äther (Mine)' }],
      encounters: ['Route 203', 'Oreburgh-Mine'],
    },
    {
      id: 'arena-erzelingen', title: 'Arena Erzelingen', kind: 'gym',
      locations: ['Erzelingen', 'Oreburgh City', 'Oreburgh', 'Arena Erzelingen', 'Oreburgh Gym'],
      goal: 'Besiege Arenaleiter Veit und gewinne den Kohle-Orden.',
      recommendedLevel: [12, 14],
      todos: ['Veit herausfordern', 'Kohle-Orden erhalten', 'TM76 Steinkante abholen'],
      trainers: [
        { name: 'Veit', title: 'Arenaleiter · Gestein', danger: true, team: [{ name: 'Geowaz', level: 12 }, { name: 'Onix', level: 12 }, { name: 'Koknodon', level: 14 }] },
      ],
      gym: {
        leader: 'Veit', type: 'Gestein', badge: 'Kohle-Orden',
        recommendedTypes: ['Wasser', 'Pflanze', 'Kampf', 'Boden', 'Stahl'],
        dangerMons: ['Koknodon (Lv14) – Kopfnuss trifft hart'],
        keyMoves: ['Steinwurf', 'Kopfnuss'],
      },
    },
    {
      id: 'route204-floraido', title: 'Route 204 & Floraido', kind: 'town',
      locations: ['Floraido', 'Floaroma Town', 'Floaroma', 'Route 204'],
      goal: 'Erreiche Floraido und befreie das Kraftwerk-Tal.',
      recommendedLevel: [10, 14],
      todos: ['Route 204 nach Norden', 'Floraido-Blumenwiese besuchen', 'Honig-Salbei für Honig kaufen', 'Galaktik-Rüpel am Tor zum Kraftwerk-Tal besiegen'],
      items: [{ name: 'Salbei-Set', note: 'Honig für Honigbäume' }, { name: 'Beeren (Blumenwiese)' }],
      hiddenItems: [{ name: 'Verstecktes Sonderbonbon (Route 204)' }],
      optionalAreas: ['Floraido-Blumenwiese'],
      encounters: ['Route 204', 'Route 205'],
    },
    {
      id: 'kraftwerk-tal', title: 'Kraftwerk-Tal (Team Galaktik)', kind: 'misc',
      locations: ['Kraftwerk-Tal', 'Valley Windworks', 'Windkraftwerk'],
      goal: 'Besiege Galaktik-Kommandantin Mars im Kraftwerk.',
      recommendedLevel: [12, 16],
      todos: ['Werks-Schlüssel vom Galaktik-Rüpel holen', 'Ins Kraftwerk eindringen', 'Kommandantin Mars besiegen'],
      trainers: [
        { name: 'Mars', title: 'Team Galaktik · Kommandantin', danger: true, team: [{ name: 'Zubat', level: 14 }, { name: 'Sheinux', level: 16 }] },
      ],
      items: [{ name: 'TM (Kraftwerk)' }],
      encounters: ['Route 205'],
    },
    {
      id: 'route205-ewigwald', title: 'Route 205 & Ewig-Wald', kind: 'forest',
      locations: ['Ewig-Wald', 'Eterna Forest', 'Route 205'],
      goal: 'Reise mit Aromilie durch den Ewig-Wald nach Ewigenau.',
      recommendedLevel: [14, 18],
      todos: ['Mit der Wanderin Aromilie durch den Wald', 'Doppelkämpfe gegen die Käfersammler', 'Alte Villa (optional) erkunden'],
      items: [{ name: 'TM Schleuder' }, { name: 'Diverse Tränke' }],
      hiddenItems: [{ name: 'Versteckter Äther (Wald)' }],
      optionalAreas: ['Alte Villa'],
      encounters: ['Route 205', 'Ewig-Wald'],
    },
    {
      id: 'arena-ewigenau', title: 'Arena Ewigenau & Galaktik-Gebäude', kind: 'gym',
      locations: ['Ewigenau', 'Eterna City', 'Eterna', 'Arena Ewigenau', 'Eterna Gym'],
      goal: 'Besiege Hardy und stürme das Galaktik-Gebäude.',
      recommendedLevel: [18, 22],
      todos: ['Fahrrad im Fahrradladen holen (gratis)', 'Arena Ewigenau (Drehtüren) lösen', 'Hardy besiegen → Wald-Orden', 'VM01 Zerschneider von der Statue', 'Galaktik-Gebäude: Kommandant Jupiter besiegen', 'Pokémon-Auslöscher zerstören'],
      trainers: [
        { name: 'Hardy', title: 'Arenaleiterin · Pflanze', danger: true, team: [{ name: 'Cherubi', level: 19 }, { name: 'Sarzenia', level: 19 }, { name: 'Roserade', level: 22 }] },
        { name: 'Jupiter', title: 'Team Galaktik · Kommandantin', danger: true, team: [{ name: 'Zubat', level: 18 }, { name: 'Skorgla', level: 20 }] },
      ],
      gym: {
        leader: 'Hardy', type: 'Pflanze', badge: 'Wald-Orden',
        recommendedTypes: ['Feuer', 'Flug', 'Eis', 'Käfer', 'Gift'],
        dangerMons: ['Roserade (Lv22) – Gigasauger & Giftspitzen'],
        keyMoves: ['Rasierblatt', 'Gigasauger', 'Aromakur'],
      },
      tms: [{ name: 'VM01 Zerschneider', note: 'Von der Statue' }],
      encounters: ['Route 211', 'Kraterberg'],
    },
    {
      id: 'route206-208-herzhofen', title: 'Radweg & Herzhofen', kind: 'town',
      locations: ['Herzhofen', 'Hearthome City', 'Hearthome', 'Route 206', 'Route 207', 'Route 208'],
      goal: 'Erreiche Herzhofen — die Arena ist noch geschlossen.',
      recommendedLevel: [20, 24],
      todos: ['Über den Radweg (Route 206) & Route 207/208', 'Weggabelungshöhle (VM Zertrümmerer optional)', 'In Herzhofen ein Pokémon-Ei erhalten', 'Rivalenkampf vor der Kontesthalle', 'Pokétch-App & Kontesthalle besuchen'],
      trainers: [
        { name: 'Rivale', title: 'Herzhofen', team: [{ name: 'Staravia', level: 23 }, { name: 'Starter', level: 25 }] },
      ],
      items: [{ name: 'Pokémon-Ei', note: 'Vom Mann in Herzhofen' }],
      optionalAreas: ['Kontesthalle', 'Weggabelungshöhle'],
      encounters: ['Route 208', 'Route 209'],
    },
    {
      id: 'route209-fleetburg', title: 'Route 209 & Fleetburg', kind: 'town',
      locations: ['Fleetburg', 'Solaceon Town', 'Solaceon', 'Route 209', 'Ödnisturm', 'Lost Tower'],
      goal: 'Erkunde Fleetburg und den Ödnisturm.',
      recommendedLevel: [22, 26],
      todos: ['Ödnisturm durchqueren (oben: VM-Item)', 'Fleetburg: Pokémon-Pension & Unform-Ruinen', 'Über Route 210 (Nebel) Richtung Schleiede'],
      items: [{ name: 'VM (Ödnisturm-Region)' }, { name: 'Mondstein (Ödnisturm)' }],
      hiddenItems: [{ name: 'Versteckte Items im Ödnisturm' }],
      optionalAreas: ['Unform-Ruinen', 'Pokémon-Pension'],
      encounters: ['Route 209', 'Route 210', 'Route 215'],
    },
    {
      id: 'arena-schleiede', title: 'Arena Schleiede & Galaktik-Zentrale', kind: 'gym',
      locations: ['Schleiede', 'Veilstone City', 'Veilstone', 'Arena Schleiede', 'Veilstone Gym'],
      goal: 'Besiege Hilda und kundschafte die Galaktik-Zentrale aus.',
      recommendedLevel: [27, 30],
      todos: ['Arena Schleiede (Kampf) lösen', 'Hilda besiegen → Fels-Orden', 'Kaufhaus & Spielhalle besuchen', 'Galaktik-Kommandozentrale auskundschaften', 'TM Schaufler (Kaufhaus-Dach)'],
      trainers: [
        { name: 'Hilda', title: 'Arenaleiterin · Kampf', danger: true, team: [{ name: 'Meditie', level: 28 }, { name: 'Maschock', level: 29 }, { name: 'Lucario', level: 32 }] },
      ],
      gym: {
        leader: 'Hilda', type: 'Kampf', badge: 'Fels-Orden',
        recommendedTypes: ['Flug', 'Psycho', 'Fee', 'Geist'],
        dangerMons: ['Lucario (Lv32) – Aurasphäre & Nahkampf'],
        keyMoves: ['Nahkampf', 'Aurasphäre', 'Steigerungshieb'],
      },
      optionalAreas: ['Kaufhaus Schleiede', 'Spielhalle'],
    },
    {
      id: 'route213-sumpfwiesen', title: 'Sumpfwiesen & Arena (Wasser)', kind: 'gym',
      locations: ['Sumpfwiesen', 'Pastoria City', 'Pastoria', 'Route 213', 'Route 212'],
      goal: 'Besiege den Wasser-Arenaleiter und gewinne den Sumpf-Orden.',
      recommendedLevel: [28, 33],
      todos: ['Über Route 213 nach Sumpfwiesen', 'Großmoor-Safari (optional)', 'Galaktik-Rüpel auf dem Steg besiegen', 'Wasser-Arena lösen → Sumpf-Orden'],
      trainers: [
        { name: 'Wicky', title: 'Arenaleiter · Wasser', danger: true, team: [{ name: 'Gastrodon', level: 30 }, { name: 'Quagsire', level: 27 }, { name: 'Floatzel', level: 33 }] },
      ],
      gym: {
        leader: 'Wicky', type: 'Wasser', badge: 'Sumpf-Orden',
        recommendedTypes: ['Pflanze', 'Elektro'],
        dangerMons: ['Floatzel (Lv33) – schnell, Aquahieb', 'Gastrodon – Elektro wirkungslos'],
        keyMoves: ['Aquahieb', 'Surfer'],
      },
      optionalAreas: ['Großmoor-Safari'],
      encounters: ['Route 212', 'Route 213'],
    },
    {
      id: 'arena-herzhofen-geist', title: 'Arena Herzhofen (Geist)', kind: 'gym',
      locations: ['Arena Herzhofen', 'Hearthome Gym', 'Lamina'],
      goal: 'Kehre nach Herzhofen zurück und besiege Lamina.',
      recommendedLevel: [32, 36],
      todos: ['Anwesen auf Route 212 (optional)', 'Zurück nach Herzhofen', 'Quiz-Arena lösen', 'Lamina besiegen → Relikt-Orden'],
      trainers: [
        { name: 'Lamina', title: 'Arenaleiterin · Geist', danger: true, team: [{ name: 'Driftlon', level: 32 }, { name: 'Kramurx', level: 34 }, { name: 'Mismagius', level: 36 }] },
      ],
      gym: {
        leader: 'Lamina', type: 'Geist', badge: 'Relikt-Orden',
        recommendedTypes: ['Unlicht', 'Geist'],
        dangerMons: ['Mismagius (Lv36) – Spukball & Standpauke'],
        keyMoves: ['Spukball', 'Standpauke'],
      },
      optionalAreas: ['Anwesen (Route 212)'],
    },
    {
      id: 'kraterberg-kanalave', title: 'Kraterberg & Kanalave', kind: 'gym',
      locations: ['Kanalave', 'Canalave City', 'Canalave', 'Kraterberg', 'Mt. Coronet', 'Route 211'],
      goal: 'Durchquere den Kraterberg und besiege den Stahl-Arenaleiter.',
      recommendedLevel: [36, 40],
      todos: ['Kraterberg (Route 207/211) durchqueren', 'Kanalave: Bibliothek & Hafen', 'Eiseninsel erkunden (VM Stärke / Item)', 'Stahl-Arena lösen → Minen-Orden'],
      trainers: [
        { name: 'Adam', title: 'Arenaleiter · Stahl', danger: true, team: [{ name: 'Stahlos', level: 37 }, { name: 'Bollterus', level: 41 }] },
      ],
      gym: {
        leader: 'Adam', type: 'Stahl', badge: 'Minen-Orden',
        recommendedTypes: ['Feuer', 'Kampf', 'Boden'],
        dangerMons: ['Bollterus (Lv41) – hohe Verteidigung, Steinkante', 'Stahlos – Erdbeben'],
        keyMoves: ['Erdbeben', 'Steinkante', 'Eisenschädel'],
      },
      optionalAreas: ['Eiseninsel', 'Kanalave-Bibliothek'],
      encounters: ['Kraterberg', 'Route 218'],
    },
    {
      id: 'seen-krise', title: 'Seen-Krise (Team Galaktik)', kind: 'misc',
      locations: ['See Eintracht', 'Lake Valor', 'See Vryheit', 'Lake Verity', 'See Tobel', 'Lake Acuity'],
      goal: 'Vereitle Team Galaktiks Angriff auf die drei Seen.',
      recommendedLevel: [38, 42],
      todos: ['See Eintracht: Explosion untersuchen', 'Galaktik-Kommandozentrale in Schleiede stürmen', 'Saturn besiegen', 'Den Kommandanten zum Eispfad folgen'],
      trainers: [
        { name: 'Saturn', title: 'Team Galaktik · Kommandant', danger: true, team: [{ name: 'Golbat', level: 38 }, { name: 'Toxiquak', level: 40 }] },
      ],
      optionalAreas: ['Galaktik-Kommandozentrale'],
    },
    {
      id: 'eispfad-blizzach', title: 'Eispfad & Blizzach', kind: 'gym',
      locations: ['Blizzach', 'Snowpoint City', 'Snowpoint', 'Eispfad', 'Route 216', 'Route 217'],
      goal: 'Überstehe den Eispfad und besiege die Eis-Arena.',
      recommendedLevel: [40, 44],
      todos: ['Eispfad (Route 216/217) im Schneesturm durchqueren', 'Blizzach: Eis-Arena lösen → Eiszapfen-Orden', 'Frostkammer-Tempel (Story) besuchen'],
      trainers: [
        { name: 'Frieda', title: 'Arenaleiterin · Eis', danger: true, team: [{ name: 'Sniebel', level: 40 }, { name: 'Piorus', level: 40 }, { name: 'Rexblisar', level: 44 }] },
      ],
      gym: {
        leader: 'Frieda', type: 'Eis', badge: 'Eiszapfen-Orden',
        recommendedTypes: ['Feuer', 'Kampf', 'Stahl', 'Gestein'],
        dangerMons: ['Rexblisar (Lv44) – Eishieb & Auftauen'],
        keyMoves: ['Eishieb', 'Lawine'],
      },
      optionalAreas: ['Frostkammer-Tempel'],
    },
    {
      id: 'speersaeule-zerrwelt', title: 'Speersäule & Zerrwelt', kind: 'misc',
      locations: ['Speersäule', 'Spear Pillar', 'Zerrwelt', 'Distortion World', 'Kraterberg-Spitze'],
      goal: 'Stoppe Zyrus an der Speersäule und in der Zerrwelt.',
      recommendedLevel: [44, 48],
      todos: ['Kraterberg zur Speersäule erklimmen', 'Galaktik-Kommandanten (Mars & Jupiter) besiegen', 'Zyrus an der Speersäule stellen', 'Giratina in der Zerrwelt fangen/besiegen'],
      trainers: [
        { name: 'Zyrus', title: 'Team Galaktik · Boss', danger: true, team: [{ name: 'Galagladi', level: 46 }, { name: 'Hippoterus', level: 46 }, { name: 'Kralle', level: 48 }] },
        { name: 'Giratina', title: 'Legendär · Zerrwelt', danger: true, team: [{ name: 'Giratina', level: 47 }] },
      ],
      optionalAreas: ['Zerrwelt (Rätsel)'],
    },
    {
      id: 'sonnewik', title: 'Sonnewik (Arena Elektro)', kind: 'gym',
      locations: ['Sonnewik', 'Sunyshore City', 'Sunyshore', 'Route 222', 'Route 223'],
      goal: 'Besiege Volkner und gewinne den achten Orden.',
      recommendedLevel: [46, 50],
      todos: ['Über Route 222 nach Sonnewik (VM Surfer)', 'Leuchtturm besuchen', 'Volkner in der Elektro-Arena besiegen → Leuchtturm-Orden'],
      trainers: [
        { name: 'Volkner', title: 'Arenaleiter · Elektro', danger: true, team: [{ name: 'Blitza', level: 46 }, { name: 'Raichu', level: 46 }, { name: 'Luxtra', level: 48 }, { name: 'Elevoltek', level: 50 }] },
      ],
      gym: {
        leader: 'Volkner', type: 'Elektro', badge: 'Leuchtturm-Orden',
        recommendedTypes: ['Boden', 'Pflanze (gegen Wasser-Decks)'],
        dangerMons: ['Elevoltek (Lv49) – Feuersturm & Donnerblitz', 'Luxtra (Lv49) – schnell'],
        keyMoves: ['Donnerblitz', 'Ladungsstoß'],
      },
      encounters: ['Route 222', 'Route 223'],
    },
    {
      id: 'siegesstrasse', title: 'Siegesstraße', kind: 'cave',
      locations: ['Siegesstraße', 'Victory Road', 'Route 224', 'Pokémon Liga'],
      goal: 'Durchquere die Siegesstraße zur Pokémon-Liga.',
      recommendedLevel: [48, 53],
      todos: ['Siegesstraße (VM Stärke / Zertrümmerer / Surfer) lösen', 'Letzter Rivalenkampf am Ausgang', 'Items & TMs einsammeln', 'Team & Beleber auffüllen'],
      trainers: [
        { name: 'Rivale', title: 'Finaler Kampf', danger: true, team: [{ name: 'Staraptor', level: 52 }, { name: 'Heiteira', level: 51 }, { name: 'Starter', level: 53 }] },
      ],
      tms: [{ name: 'Diverse TMs (Siegesstraße)' }],
      hiddenItems: [{ name: 'Versteckte Items in der Siegesstraße' }],
    },
    {
      id: 'top-vier', title: 'Top Vier', kind: 'misc',
      locations: ['Pokémon Liga', 'Top Vier', 'Elite Four', 'Liga'],
      goal: 'Besiege die Top Vier ohne Pause.',
      recommendedLevel: [53, 60],
      todos: ['Aaron · Käfer besiegen', 'Teresa · Boden besiegen', 'Ignaz · Feuer besiegen', 'Lucian · Psycho besiegen', 'Vorräte vorher auffüllen (keine Pause dazwischen!)'],
      trainers: [
        { name: 'Aaron', title: 'Top Vier · Käfer', danger: true, team: [{ name: 'Skorgro', level: 53 }, { name: 'Drapion', level: 57 }] },
        { name: 'Teresa', title: 'Top Vier · Boden', danger: true, team: [{ name: 'Rihornior', level: 55 }, { name: 'Hippoterus', level: 59 }] },
        { name: 'Ignaz', title: 'Top Vier · Feuer', danger: true, team: [{ name: 'Panferno', level: 55 }, { name: 'Magbrant', level: 58 }] },
        { name: 'Lucian', title: 'Top Vier · Psycho', danger: true, team: [{ name: 'Simsala', level: 53 }, { name: 'Bronzong', level: 59 }] },
      ],
    },
    {
      id: 'cynthia', title: 'Champ Cynthia', kind: 'misc',
      locations: ['Cynthia', 'Champion', 'Champ'],
      goal: 'Besiege Champ Cynthia und werde Sieger der Sinnoh-Liga.',
      recommendedLevel: [58, 64],
      todos: ['Cynthias Team kennen: vielseitig, kein klarer Konter', 'Knakrack (Lv62) ist die größte Gefahr', 'Eis gegen Knakrack & Schlapor bereithalten', 'Cynthia besiegen → Hall of Fame'],
      trainers: [
        {
          name: 'Cynthia', title: 'Champ · Sinnoh-Liga', danger: true,
          team: [
            { name: 'Kryppuk', level: 58 }, { name: 'Roserade', level: 58 }, { name: 'Togekiss', level: 60 },
            { name: 'Lucario', level: 63 }, { name: 'Milotic', level: 58 }, { name: 'Knakrack', level: 66 },
          ],
        },
      ],
      gym: {
        leader: 'Cynthia', type: 'Vielseitig', badge: 'Hall of Fame',
        recommendedTypes: ['Eis', 'Fee', 'Kampf', 'Drache'],
        dangerMons: ['Knakrack (Lv66) – Drachenklaue & Erdbeben', 'Togekiss (Lv60) – Aurasphäre & Luftschnitt', 'Lucario (Lv63)'],
        keyMoves: ['Drachenklaue', 'Erdbeben', 'Aurasphäre'],
      },
    },
  ],
}
